name: Acceptance-tests
on:
  workflow_run:
    workflows: ["Commit-tests"]
    types:
      - completed
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: acceptance-tests
        run: robot tests/acceptance_test/dummy_test.robot

