name: Build-binaries
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "this is a dummy end point"

