name: Non-functional-tests
on:
  workflow_run:
    workflows: ["Acceptance-tests"]
    types:
      - completed
jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: non-functional-tests
        run: echo "this is a dummy end point"

